@file:JvmName("Constants")
package com.dashx.sdk


const val PACKAGE_NAME = "com.dashx.sdk"
const val DEFAULT_INSTANCE = "default"

const val SHARED_PREFERENCES_PREFIX = PACKAGE_NAME
const val SHARED_PREFERENCES_KEY_BUILD = "$SHARED_PREFERENCES_PREFIX.$DEFAULT_INSTANCE.build"
const val SHARED_PREFERENCES_KEY_VERSION = "$SHARED_PREFERENCES_PREFIX.$DEFAULT_INSTANCE.version"
const val SHARED_PREFERENCES_KEY_ANONYMOUS_UID = "$SHARED_PREFERENCES_PREFIX.$DEFAULT_INSTANCE.anonymous_uid"
